networks:
  safira-net:
    name: safira-net
    driver: bridge

volumes:
  n8n-data:
  venom-data:
  ollama-data:
  whisper-models:
  pgdata:
  tts-cache:
  jira-data:


services:
  safira-core:
    image: n8nio/n8n
    ports: ["5678:5678"]
    networks: [safira-net]
    volumes:
      - n8n-data:/home/node/.n8n
    env_file: .env
    depends_on:
      - postgree
      - whatsapp
      - llm-ollama
    restart: unless-stopped

  whatsapp:
    build:
      context: ./build/venom
      dockerfile: Dockerfile
    ports: ["3000:3000"]
    networks: [safira-net]
    volumes:
      - venom-data:/app/sessions
    env_file: .env
    environment:
      - WEBHOOK_URL=${WEBHOOK_URL}
    restart: unless-stopped

  llm-ollama:
    image: ollama/ollama
    ports: ["11434:11434"]
    networks: [safira-net]
    volumes:
      - ollama-data:/models
    env_file: .env
    restart: unless-stopped

  whisper:
    build: ./build/whisper
    ports: ["9000:9000"]
    networks: [safira-net]
    volumes:
      - whisper-models:/models
    env_file: .env
    environment:
      WHISPER_MODEL: large-v3
      WHISPER_LANGUAGE: pt
      WHISPER_DEVICE: cpu
      WHISPER_COMPUTE_TYPE: int8
    depends_on:
      - safira-core
      - llm-ollama
    restart: unless-stopped

  tts:
    build: ./build/tts
    ports: ["5000:5000"]
    networks: [safira-net]
    volumes:
      - tts-cache:/root/.local/share/tts
    env_file: .env
    environment:
      MODEL_NAME: tts_models/multilingual/multi-dataset/xtts_v2
      USE_CUDA: "false"
    restart: unless-stopped

  postgree:
    image: postgres:16
    ports: ["5432:5432"]
    networks: [safira-net]
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: .env
    restart: unless-stopped

  jira:
    image: atlassian/jira-software:latest
    container_name: jira
    ports:
      - "8080:8080"
    networks:
      - safira-net
    volumes:
      - jira-data:/var/atlassian/application-data/jira
      - pgdata:/var/lib/postgresql/data
      - ./build/postgree:/docker-entrypoint-initdb.d
    environment:
      - ATL_JDBC_URL=jdbc:postgresql://postgree:5432/jiradb
      - ATL_JDBC_USER=${POSTGRES_USER}
      - ATL_JDBC_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgree
    restart: unless-stopped
