networks:
  safira-net:
    name: safira-net
    driver: bridge

volumes:
  n8n-data:
  ollama-data:
  whisper-models:
  pgdata:
  tts-cache:
  jira-data:
  wiki-data:
  evolution_store:
  evolution_instances:
  evolution-audio: 
  redis-data:


services:
  safira-core:
    image: n8nio/n8n
    container_name: Safira-n8n
    ports: ["5678:5678"]
    networks: [safira-net]
    volumes:
      - n8n-data:/home/node/.n8n
      - ./tmp/news:/tmp/news
    env_file: .env
    depends_on:
      - postgree
      - llm-ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

  llm-ollama:
    image: ollama/ollama
    container_name: Safira-Ollama
    ports: ["11434:11434"]
    networks: [safira-net]
    volumes:
      - ollama-data:/models
      - ollama-data:/root/.ollama
    env_file: .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s


  whisper:
    build: ./build/whisper
    container_name: Safira-STT
    ports: ["9000:9000"]
    networks: [safira-net]
    volumes:
      - whisper-models:/models
    env_file: .env
    environment:
      WHISPER_MODEL: large-v3
      WHISPER_LANGUAGE: pt
      WHISPER_DEVICE: cpu
      WHISPER_COMPUTE_TYPE: int8 
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s


  tts:
    build: ./build/tts
    container_name: Safira-TTS
    ports: ["5000:5000"]
    networks: [safira-net]
    volumes:
      - tts-cache:/root/.local/share/tts
    env_file: .env
    environment:
      MODEL_NAME: tts_models/multilingual/multi-dataset/xtts_v2
      USE_CUDA: "false"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s


  postgree:
    image: postgres:16
    container_name: Safira-DB
    ports: ["5432:5432"]
    networks: [safira-net]
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5


  jira:
    image: atlassian/jira-software:latest
    container_name: Safira-Jira
    ports:
      - "8080:8080"
    networks:
      - safira-net
    volumes:
      - jira-data:/var/atlassian/application-data/jira
      - ./build/postgree:/docker-entrypoint-initdb.d
    environment:
      - ATL_JDBC_URL=jdbc:postgresql://postgree:5432/jiradb
      - ATL_JDBC_USER=${POSTGRES_USER}
      - ATL_JDBC_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgree
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s


  wikijs:
    image: requarks/wiki:2
    container_name: Safira-Docs
    ports:
      - "3001:3000"
    networks:
      - safira-net
    environment:
      DB_TYPE: postgres
      DB_HOST: postgree
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_NAME: wikidb
    depends_on:
      - postgree
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

  evolution-api:
    image: atendai/evolution-api
    container_name: Safira-EvolutionAPI
    ports:
      - "8085:8080"
    networks:
      - safira-net
    volumes:
      - evolution-audio:/app/audios
      - evolution_store:/evolution/store
      - evolution_instances:/evolution/instances
    environment:
      - LICENSE_KEY=${EVOLUTION_LICENSE_KEY}
      - INTERFACE=all
      - WEBHOOK_URL_EVO=${WEBHOOK_URL_EVO}

      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgree:5432/${POSTGRES_DB}?schema=public
      - DATABASE_CONNECTION_CLIENT_NAME=SafiraEvolutionClient

      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://redis:6379/0
      - CACHE_REDIS_PREFIX_KEY=evolution
      - CACHE_LOCAL_ENABLED=false

    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

  redis:
      image: redis:7
      container_name: safira-redis
      networks:
        - safira-net
      ports:
        - '6379:6379'
      volumes:
        - redis-data:/data

  instagrapi:
    build:
      context: ./build/instagrapi
      dockerfile: Dockerfile
    container_name: Safira-Instagram
    ports:
      - "8010:8000"
    networks:
      - safira-net
    volumes:
      - ./data/instagrapi:/app/session
    env_file: .env
    environment:
      - IG_USERNAME=${IG_USERNAME}
      - IG_PASSWORD=${IG_PASSWORD}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
