name: Atualiza badge do README

on:
  workflow_run:
    workflows: ["Safira CI - Develop"]
    types:
      - completed

jobs:
  badge:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório na branch certa
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Atualizar badge no README
        run: |
          sed -i 's|<!-- status-badge --> !\[.*\](.*)|<!-- status-badge --> ![✅ Build Passed](https://img.shields.io/badge/build-passed-brightgreen)|' README.md
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -am "🤖 Atualizando badge após CI"
          git push origin ${{ github.event.workflow_run.head_branch }}
