name: Safira CI - Release

on:
  push:
    branches:
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run docker compose build
        run: docker compose -f docker-compose.yml up --build -d
